name: diplom
description: ")("
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^2.16.0 # Последняя стабильная версия
  firebase_auth: ^4.16.0
  shared_preferences: ^2.1.0 # Последняя стабильная версия

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - asset/image_1.png
    - asset/image_2.png
    - asset/image_3.png
    - asset/image_4.png
    - asset/image_5.png

