name: diplom
description: ")("
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  cached_network_image: ^3.0.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.0.0
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  firebase_auth: ^5.3.1
  shared_preferences: ^2.1.0
  image_picker: ^0.8.6
  permission_handler: ^10.2.0
  html: ^0.15.0





dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/image_1.png
    - assets/images/image_2.png
    - assets/images/image_3.png
    - assets/images/image_4.png
    - assets/images/image_5.png
    - assets/images/default_avatar.png
    - assets/images/default_image.png

